### ISSUE TITLE
Task를 어떻게 나눌지에 대해 의견 제시

### ISSUE THREAD

**Issue by wogns7534** [wogns7534/Project2#1]
main.c 파일을 확인하고 Task를 어떻게 나누면 좋을지 의견 제시해 주세요.

**Comment by pdache** [comment]
기능 1,2,3,4 순서대로 하나씩 하고 5,6은 두명씩 짝 지어서 하면 좋을 것 같네요

**Comment by Hyeon9mak** [comment]
우선 하나씩 진행한 후, 진행속도가 빠른 사람이 나머지를 진행하면 어떨까 싶습니다.

**Comment by wlsgh6346** [comment]
1,2번 한명
3,4번 한명
5번 한명
6번 한명
이 후 취합 후 4명이서 검토

**Comment by wogns7534** [comment]
그럼 우선 1~6번 기능별로 Task를 나누겠습니다.
각자 몇 번 기능을 담당하고 싶은지 의견 제시해 주세요.

**Comment by pdache** [comment]
1. 파일 정보 받아 오기
2. 파일 시간 받아 오기
3. 파일 사이즈 비교
4. 파일 블락 수 비교
5. 파일 수정 날짜(월/일) 비교
6. 파일 수정 시간(시/분) 비교

**Comment by pdache** [comment]
저는 1,2번 하겠습니다.

**Comment by wlsgh6346** [comment]
저는 3,4번 하겠습니다.

**Comment by wogns7534** [comment]
저도 1, 2번이 하고 싶은걸요

**Comment by pdache** [comment]
그러면 제가 5번 하겠습니다.

**Comment by Hyeon9mak** [comment]
남는 6번 하도록 하겠습니다.

**Comment by wogns7534** [comment]
최종적으로
- 1,2번 주재훈
- 3,4번 최진호
- 5번 박동현
- 6번 최현구  

로 정리되었습니다.
Task를 모두 나누었으므로, 이 이슈는 닫도록 하겠습니다.
