### ISSUE TITLE
4번 기능에 대한 코드 리뷰

### ISSUE THREAD

**Issue by wlsgh6346** [wogns7534/Project2#10]
작성한 4번 코드의 대한 리뷰

**Comment by wogns7534** [comment]
마일스톤 할당 했습니다. 주기적으로 이슈 업데이트 해주세요.

**Comment by wlsgh6346** [comment]
# 4번 기능에 대한 코드 리뷰 및 테스트
4번 기능에 대해 코드 리뷰와 테스트를 진행합니다.  
테스트에 사용된 코드는 아래와 같습니다.

## 테스트에 사용된 코드
![image](https://user-images.githubusercontent.com/51193356/82211805-6805db80-994c-11ea-9abe-5a983de1e6ce.png)
![image](https://user-images.githubusercontent.com/51193356/82211785-5fada080-994c-11ea-9051-213f5405656c.png)

## 블락 개수 비교 (text1 = text2)
![image](https://user-images.githubusercontent.com/51193356/82212534-ab147e80-994d-11ea-9d47-ffaa5a1a5ef0.png)

## 블락 개수 비교 (text1 > text2)
![image](https://user-images.githubusercontent.com/51193356/82212485-946e2780-994d-11ea-9c3d-4551ede9b179.png)

## 블락 개수 비교 (text1 < text2)
![image](https://user-images.githubusercontent.com/51193356/82212394-743e6880-994d-11ea-9f94-11425d93475c.png)

## 코드 리뷰
변경사항 없습니다.
