### ISSUE TITLE
1번 기능에 대한 기반 기술 조사

### ISSUE THREAD

**Issue by wogns7534** [wogns7534/Project2#11]
1번 기능에 대한 기반 기술(함수) 조사를 진행할 예정

**Comment by wogns7534** [comment]
# 1번 기능 : 파일1과 2의 정보를 가져오는 함수
파일에 대한 정보를 알아보는 stat 함수를 활용한다.  **sys/stat.h** 헤더 파일에 포함되어 있다.  

## 함수 원형
``` c
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

int stat(const char *path, struct stat *buf);
```

## 함수 파라미터
``` c
path // 파일 명 또는 파일에 대한 경로
buf // 파일의 상태 및 정보를 저장할 구조체
```

## 함수 반환 값
``` c
0 // 정상적인 파일 정보 조회
-1 // 파일 정보 조회 중 오류 발생
```

**Comment by pdache** [comment]
깔끔하네요. 기반 기술 조사 양식 공유해주시면 같은 양식으로 조사글 업로드 할게영~

**Comment by wogns7534** [comment]
> 깔끔하네요. 기반 기술 조사 양식 공유해주시면 같은 양식으로 조사글 업로드 할게영~

@pdache 소스코드란 때문에 양식 공유가 잘 안되네요.
비슷하게만 해주면 될 것 같습니다.

일단 1, 2번 사전조사는 끝났으니 close할게요.
