### ISSUE TITLE
1번 기능 코드 작성

### ISSUE THREAD

**Issue by wogns7534** [wogns7534/Project2#12]
# 1번 기능 코드 작성
1번 기능에 관련하여 코드 작성 진행사항을 기록할 이슈

**Comment by pdache** [comment]
5번 기능 수행을 위해서 1, 2번 기능이 우선 진행되어야 합니다. 빨리 진행해주세요.

**Comment by Hyeon9mak** [comment]
> 5번 기능 수행을 위해서 1, 2번 기능이 우선 진행되어야 합니다. 빨리 진행해주세요.

스켈레톤 코드에 전역변수들이 선언되어 있는데, 상관없이 진행하면 되지 않을까요?

**Comment by pdache** [comment]
> > 5번 기능 수행을 위해서 1, 2번 기능이 우선 진행되어야 합니다. 빨리 진행해주세요.
> 
> 스켈레톤 코드에 전역변수들이 선언되어 있는데, 상관없이 진행하면 되지 않을까요?

코드 작성은 가능한데, 테스트가 불가능해요.

**Comment by Hyeon9mak** [comment]
> > > 5번 기능 수행을 위해서 1, 2번 기능이 우선 진행되어야 합니다. 빨리 진행해주세요.
> > 
> > 
> > 스켈레톤 코드에 전역변수들이 선언되어 있는데, 상관없이 진행하면 되지 않을까요?
> 
> 코드 작성은 가능한데, 테스트가 불가능해요.

그러네... 이 부분은 상의가 필요할 것 같습니다. 그럼 일단 코드를 작성하는 것만 이슈에 업로드 하고,  
리뷰 및 테스트는 가장 마지막 단계에 진행하는 걸로 해야겠습니다.

**Comment by wogns7534** [comment]
지금 확인했습니다. 최대한 빨리 진행해보도록 하겠습니다~

**Comment by wogns7534** [comment]
``` c
//파일 1의 정보를 가져오는 함수 작성

void filestat1(){
	const char* filename = "./text1";

	if (stat(filename, &stat1)) {
		printf("This file does not exist.\n");
	}
}

//파일 2의 정보를 가져오는 함수 작성
void filestat2(){
	const char* filename = "./text2";

	if (stat(filename, &stat2)) {
		printf("This file does not exist.\n");
	}
}
```
