### ISSUE TITLE
6번 기능에 대한 기반 기술 조사

### ISSUE THREAD

**Issue by Hyeon9mak** [wogns7534/Project2#17]
## 6번 기능에 대한 기반 기술 조사
6번 기능에 대한 기반 기술 조사를 진행하겠습니다.

**Comment by wogns7534** [comment]
마일스톤과 Assigness 지정했습니다. 주기적인 업데이트 바랍니다.

**Comment by Hyeon9mak** [comment]
# 6번 기능 : 두 개의 파일간 수정 시간(시/분) 비교
두 개의 파일간 수정 시간을 비교하기 위해서는 파일정보 구조체(stat)로부터 가져온  
수정시간 멤버변수(mtime)를 필요로 한다.  
이 때문에 **sys/stat.h** 헤더 파일을 필요로 하며,  
mtime 멤버변수의 값을 날짜/시간으로 정리하기 위해서 localtime 함수가 사용되므로  
**time.h** 헤더 파일 또한 필요해지는 것을 알 수 있다.

## 수정 시간을 구하는 방법
``` c
time1->tm_hour // time1은 file1의 stat구조체에서 가져온 mtime 정보
time1->tm_min // time1은 file1의 stat구조체에서 가져온 mtime 정보
```

## 수정 시간 비교 방법
시(hour)를 먼저 비교하고, 둘의 시(hour)가 같을 경우 분(min)을 비교한다.
``` c
// 우선 hour를 비교
if (time1->tm_hour > time2->tm_hour) // file1 이 더 나중에 수정
else if (time1->tm_hour < time2->tm_hour) {} // file2 가 더 나중에 수정
else {    // 둘의 수정 '시간'이 같을 때
    if (time1->tm_min > time2->tm_min) // file1 이 더 나중에 수정
    else if (time1->tm_min < time2->tm_min) // file2 가 더 나중에 수정
    else // 둘의 수정 시간이 완벽히 일치함
}
```
