### ISSUE TITLE
5번 기능에 대한 기반 기술 조사

### ISSUE THREAD

**Issue by pdache** [wogns7534/Project2#2]
필요한 함수에 대한 조사 진행

**Comment by wogns7534** [comment]
마일스톤 5번 할당했습니다. 함수 조사를 진행하는대로 이슈 업데이트 해주세요.

**Comment by pdache** [comment]
# 5번 기능 : 파일1과 2의 수정날짜를 가져오는 함수
파일이 가장 마지막에 수정된 날짜를 가져오는 함수이다.  
2번 기능에서 가져오는 시간정보 (st_mtime)을 이용한다. 이 때 mtime은 modification time을 의미한다.  
**time.h** 헤더파일과 **sys/stat.h** 헤더파일을 이용하여 구할 수 있다.

## 두 개 파일의 수정 날짜를 비교하는 방법
'월' 에 해당하는 값을 먼저 비교한다. '월'에서 차이가 발생한 경우, '일'까지 비교할 필요는 없기 때문.  
만일 '월'이 같을 경우, '일'을 비교한다. '일'까지 같을 경우, 서로 동일하다는 것을 알린다.
``` c
time->tm_mon // '월'을 구할 수 있는 방법
time->tm_mday // '일'을 구할 수 있는 방법
```

## 예시
``` c
if (time1->tm_mon < time2->tm_mon)
{
    printf("text1 is early");
}
