### ISSUE TITLE
Wiki탭 Readme.md 파일 작성의 건

### ISSUE THREAD

**Issue by wogns7534** [wogns7534/Project2#20]
Wiki탭 Readme.md 파일 작성을 누가 진행할 것인지 의견 부탁드립니다.

**Comment by Hyeon9mak** [comment]
제가 작성해본 경험이 있으므로, 작성하도록 하겠습니다.

**Comment by wogns7534** [comment]
그럼 최현구가 담당하기로 하고, 이슈 작성해서 진행상황 알려주시길 바랍니다.

**Comment by Hyeon9mak** [comment]
넵, 알겠습니다.
