### ISSUE TITLE
출력 예시에 따른 코드 재작성 요청

### ISSUE THREAD

**Issue by pdache** [wogns7534/Project2#28]
강의자료에 따르면 출력 예시가 있습니다.
그 예시에 따라 출력 부분의 코드를 재작성 해야 할 것 같습니다.
확인하시고 코드 재작성 해주세요.

**Comment by Hyeon9mak** [comment]
@pdache @wlsgh6346
두 사람 출력문이 강의자료와 조금씩 달랐던 것 같아요.
두 분 수정 후 Pull requests 다시 보내면 될 것 같습니다.

**Comment by wogns7534** [comment]
Pull requests 다시 보내주세요.
