### ISSUE TITLE
3번 기능에 대한 기반 기술 조사

### ISSUE THREAD

**Issue by wlsgh6346** [wogns7534/Project2#3]
필요한 함수 조사

**Comment by wogns7534** [comment]
마일스톤 할당 했습니다. 주기적으로 이슈 업데이트 해주세요.

**Comment by wlsgh6346** [comment]
# 3번 기능 : 두 개의 파일의 크기를 비교하는 함수
3번의 기능은 두 개의 파일의 크기를 비교하는 함수입니다.  
1번 기능으로부터 얻어온 파일정보 구조체에서 파일의 크기를 추출하여 파일간 크기를 비교할 수 있습니다.  
파일의 크기를 담고 있는 멤버변수는 **st_size** 입니다.
이 때문에 **sys/stat.h** 헤더파일을 필요로 한다고 볼 수 있습니다.

## 파일의 크기를 구하는 방법
``` c
stat1.st_size // stat1은 stat 구조체
stat2.st_size // stat2는 stat 구조체
```

## 파일의 크기를 비교하는 방법
``` c
if (stat1.st_size > stat2.st_size)
{
  // file1의 크기가 더 크다면
}
else if (stat1.st_size < stat2.st_size)
{
  // file2의 크기가 더 크다면
}
else
{
  // 둘의 크기가 같다면
}
```
