### ISSUE TITLE
5번 기능 테스팅 및 코드 리뷰

### ISSUE THREAD

**Issue by pdache** [wogns7534/Project2#6]
기능 구현 완료 후 테스팅
테스팅 후 코드 리뷰

**Comment by wogns7534** [comment]
마일스톤 할당 했습니다. 주기적으로 이슈 업데이트 해주세요.

**Comment by pdache** [comment]
# 5번 기능 테스팅 및 코드 리뷰
5번 기능에 대해 테스트 및 코드 리뷰를 진행했다.

# 테스트에 사용된 코드
``` c
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>

struct stat stat1, stat2;
struct tm *time1, *time2;

void filestat1();
void filestat2();
void filetime1();
void filetime2();
void sizecmp();
void blockcmp();
void datecmp();
void timecmp();

int main(){
    filestat1();
    filestat2();
    filetime1();
    filetime2();
    //sizecmp();
    //blockcmp();
    datecmp();
    //timecmp();
}

//파일 1의 정보를 가져오는 함수 작성
void filestat1(){
	const char* filename = "./text1";

	if (stat(filename, &stat1)) {
		printf("This file does not exist.\n");
	}
}

//파일 2의 정보를 가져오는 함수 작성
void filestat2(){
	const char* filename = "./text2";

	if (stat(filename, &stat2)) {
		printf("This file does not exist.\n");
	}
}

//파일 1의 시간 정보를 가져오는 함수 작성
void filetime1(){
	static struct tm time_1;
	time_1 = *(localtime(&stat1.st_mtime));
	time1 = &time_1;
}

//파일 2의 시간 정보를 가져오는 함수 작성
void filetime2(){
	static struct tm time_2;
	time_2 = *(localtime(&stat2.st_mtime));
	time2 = &time_2;
}

//두 개의 파일 수정 날짜를 비교하는 함수 작성
void datecmp(){
	
	printf("5. date compare\n");
	if (time1->tm_mon < time2->tm_mon)
		printf("text1 is early\n");
	else if (time1->tm_mon > time2->tm_mon)
		printf("text2 is early\n");
	else {									//같은 달에 수정을 한 경우, 날을 비교
		if (time1->tm_mday < time2->tm_mday)
			printf("text1 is early\n");
		else if (time1->tm_mday > time2->tm_mday)
			printf("text2 is early\n");
		else
			printf("same time\n");

	}
}
```
1, 2번 기능을 제외하면 5번 기능의 테스트에 필요하지 않았기 때문에 모두 제거하였다.

# 1. text1과 text2의 수정 날짜가 같은 경우
![image](https://user-images.githubusercontent.com/37354733/82208731-01ca8a00-9947-11ea-94d4-6016616e0cc0.png)
text1과 text2의 수정 날짜가 ls -l 명령을 통해 확인하는 것처럼 완전히 일치할 경우,  
"same time" 을 출력하는 것을 확인 할 수 있다.

# 2. text1이 text2 보다 빠를 경우
![image](https://user-images.githubusercontent.com/37354733/82209200-d6946a80-9947-11ea-9442-ad5d2ab49cde.png)
text2 의 날짜를 변경하여 테스트를 진행하였을 때, text1는 5월 18일, text2는 5월 19일로 기록되어 있기 때문에 text1이 더 빠르다는 출력문을 확인할 수 있다.

# 3. text2가 text1 보다 빠를 경우
![image](https://user-images.githubusercontent.com/37354733/82209316-0b082680-9948-11ea-9696-192c6adda927.png)
text2 가 5월 18일로 더 먼저 생성되었기 때문에, text2가 더 빠르다는 출력문을 확인할 수 있다.

# 코드 리뷰
5번 기능 (수정날짜 비교)에서는 크게 수정할 부분은 없었으나, "same time" 이라는 출력문 보다는 "same date" 라는 출력문이 더 낫지 않을까 라는 생각이 들어, 코드 수정 후 다시 한 번 커밋을 진행할 계획이다.
