### ISSUE TITLE
3번 기능에 대한 코드 리뷰

### ISSUE THREAD

**Issue by wlsgh6346** [wogns7534/Project2#7]
3번 기능의 코드에 대한 리뷰

**Comment by wogns7534** [comment]
마일스톤 할당 했습니다. 주기적으로 이슈 업데이트 해주세요.

**Comment by wlsgh6346** [comment]
# 3번 기능에 대한 코드 리뷰 및 테스트
3번 기능에 대해서 코드 리뷰와 테스트를 진행하겠습니다. 테스트 진행에 사용된 코드는 아래와 같습니다.

## 테스트 진행에 사용된 코드
![image](https://user-images.githubusercontent.com/51193356/82211120-4c4e0580-994b-11ea-987f-2f4fd39f64db.png)
![image](https://user-images.githubusercontent.com/51193356/82211089-3f311680-994b-11ea-9c29-32eaea49f314.png)

## 크기가 같은 두 파일 비교
![image](https://user-images.githubusercontent.com/51193356/82211487-df873b00-994b-11ea-8b4c-bf971c4f4822.png)
파일 크기가 0으로 서로 온전히 같은 경우 입니다.

## 크기가 다른 두 파일 비교 (text1 > text2)
![image](https://user-images.githubusercontent.com/51193356/82211588-0c3b5280-994c-11ea-8028-c7a08f027255.png)
text1의 크기는 19, text2의 크기는 0 인 크기 비교 입니다.

## 크기가 다른 두 파일 비교 (text1 < text2)
![image](https://user-images.githubusercontent.com/51193356/82211646-25440380-994c-11ea-87af-54e754951182.png)
text2의 크기는 62, text1의 크기는 19인 크기 비교 입니다.

## 코드 리뷰
변경 사항 없습니다.
