### ISSUE TITLE
4번 기능에 대한 기반 기술 조사

### ISSUE THREAD

**Issue by wlsgh6346** [wogns7534/Project2#8]
필요한 함수 조사

**Comment by wogns7534** [comment]
마일스톤 할당 했습니다. 주기적으로 이슈 업데이트 해주세요.

**Comment by wlsgh6346** [comment]
# 4번 기능 : 두 개의 파일 블락 수를 비교하는 함수
4번의 기능은 두 개 파일의 블락 수를 비교하는 함수입니다.  
3번 기능과 마찬가지로, 1번 기능으로부터 얻어온 파일정보 구조체에서  
파일의 블락 개수를 추출하여 파일간 블락 개수를 비교할 수 있습니다.  
파일의 블락 개수를 담고 있는 멤버변수는 **st_blocks** 입니다.
이 때문에 **sys/stat.h** 헤더파일을 필요로 한다고 볼 수 있습니다.

## 파일의 블락 개수를 구하는 방법
``` c
stat1.st_blocks // stat1은 stat 구조체
stat2.st_blocks // stat2는 stat 구조체
```

## 파일의 블락 개수를 비교하는 방법
``` c
if (stat1.st_blocks > stat2.st_blocks)
{
  // file1의 블락 개수가 더 많다면
}
else if (stat1.st_blocks < stat2.st_blocks)
{
  // file2의 블락 개수가 더 많다면
}
else
{
  // 둘의 블락 개수가 같다면
}
```

**Comment by wogns7534** [comment]
크기 비교가 아니라 블락 수를 비교해야 하므로 과제에 적혀있는 멤버변수를 사용하여 다시 작성해주시기 바랍니다.

**Comment by wlsgh6346** [comment]
> 크기 비교가 아니라 블락 수를 비교해야 하므로 과제에 적혀있는 멤버변수를 사용하여 다시 작성해주시기 바랍니다.

감사합니다 수정했습니다!
